feat: add harvester_cloudinit_secret
harvester/terraform-provider-harvester pull request #76
Opened 2023-03-06 06:10 UTC by FrankYang0529

Issue: https://github.com/harvester/harvester/issues/2958

## Test plan

1. Follow [PR Test Env Setup](https://github.com/harvester/terraform-provider-harvester/wiki/PR-Test-Env-Setup)
2. Create a file `main.tf`.
```
resource "harvester_cloudinit_secret" "ex1" {
  name             = "ex1"
  namespace        = "default"
  user_data_base64 = "I2Nsb3VkLWNvbmZpZwpwYWNrYWdlX3VwZGF0ZTogdHJ1ZQpwYWNrYWdlczoKICAtIHFlbXUtZ3Vlc3QtYWdlbnQKcnVuY21kOgogIC0gLSBzeXN0ZW1jdGwKICAgIC0gZW5hYmxlCiAgICAtIC0tbm93CiAgICAtIHFlbXUtZ3Vlc3QtYWdlbnQuc2VydmljZQpwYXNzd29yZDogdGVzdApjaHBhc3N3ZDoKICBleHBpcmU6IGZhbHNlCnNzaF9wd2F1dGg6IHRydWUK"
}

resource "harvester_cloudinit_secret" "ex2" {
    name = "ex2"
    namespace = "default"

    user_data    = <<-EOF
    #cloud-config
    password: test
    chpasswd:
      expire: false
    ssh_pwauth: true
    package_update: true
    packages:
      - qemu-guest-agent
    runcmd:
      - - systemctl
        - enable
        - '--now'
        - qemu-guest-agent
    EOF
    network_data = ""
}
```
3. Run `terraform apply`. Terraform should add `ex1` and `ex2` secrets to the cluster.
4. Run `terraform apply` again. Nothing change.

2023-03-19 10:30 UTC, futuretea reviewed
Also need to consider another test case：
1. apply with user_data not empty
2. change user_data to empty
3. apply again

2023-04-27 02:27 UTC, FrankYang0529 commented
> Also need to consider another test case：
> 
> 1. apply with user_data not empty
> 2. change user_data to empty
> 3. apply again

Added test case 2. Thanks.

2023-06-26 07:55 UTC, iosifnicolae2 commented
Any idea when this PR will be merged?

2023-07-27 06:39 UTC, chrisho requested changes

2023-07-27 06:39 UTC, chrisho commented on internal/provider/cloudinitsecret/resource_cloudinitsecret.go
> +		stateGetter.States[constants.FieldCloudInitSecretUserDataBase64] = ""
Should this be network data?

2023-07-27 06:39 UTC, chrisho commented on internal/provider/cloudinitsecret/resource_cloudinitsecret.go
> +			return fmt.Errorf("can't decode userdata: %v", err)
ditto

2023-07-27 06:41 UTC, chrisho commented on internal/provider/cloudinitsecret/resource_cloudinitsecret.go
> +			return fmt.Errorf("can't decode userdata: %v", err)
Should this be network data?

2023-07-27 06:41 UTC, chrisho commented on internal/provider/cloudinitsecret/resource_cloudinitsecret.go
> +		stateGetter.States[constants.FieldCloudInitSecretUserDataBase64] = ""
ditto

2023-07-27 07:07 UTC, futuretea commented on internal/provider/cloudinitsecret/resource_cloudinitsecret.go
> +			return fmt.Errorf("can't decode userdata: %v", err)
Fixed. Thanks!

2023-07-27 09:23 UTC, chrisho approved these changes
LGTM, the test cases are working fine, thanks.

2023-08-10 07:30 UTC, futuretea approved these changes

2023-08-15 09:39 UTC, guangbochen approved these changes
LGTM, and verified that the testing case works.

2023-08-15 09:41 UTC, guangbochen commented
@bk201 please take a look when u are back only; merge the PR to process the validation first, thanks.

2023-08-15 09:41 UTC, merged